In [ ]:
import pandas as pd
df = pd.read_csv('olist_sellers_dataset.csv')
df.head()

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP
2,ce3ad9de960102d0677a81f5d0bb7b2d,20031,rio de janeiro,RJ
3,c0f3eea2e14555b6faeea3dd58c1b1c3,4195,sao paulo,SP
4,51a04a8a6bdcb23deccc82b0b80742cf,12914,braganca paulista,SP

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3095 entries, 0 to 3094
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   seller_id               3095 non-null   object
 1   seller_zip_code_prefix  3095 non-null   int64
 2   seller_city             3095 non-null   object
 3   seller_state            3095 non-null   object
dtypes: int64(1), object(3)
memory usage: 96.8+ KB

In [ ]:
df['seller_id'].duplicated().sum()

np.int64(0)

In [ ]:
df['seller_city'].nunique()

593

In [ ]:
df['seller_city'] = df['seller_city'].str.lower()
df['seller_city'] = df['seller_city'].str.strip()

In [ ]:
df['seller_city'] = df['seller_city'].str.replace('são paulo', 'sao paulo')

In [ ]:
df['seller_city'] = df['seller_city'].str.split(r'[/\-,]').str[0].str.strip()

In [ ]:
df['seller_city'].value_counts().head(10)

seller_city
sao paulo         698
curitiba          127
rio de janeiro     98
belo horizonte     68
ribeirao preto     53
guarulhos          50
ibitinga           49
santo andre        46
campinas           41
maringa            40
Name: count, dtype: int64

In [ ]:
from google.colab import files

df.to_csv('olist_sellers.csv',index = False)
files.download('olist_sellers.csv')